### ISSUE TITLE
"plugin uninstall jetpack" throws an error

### ISSUE THREAD

**Issue by plesk-eponkin** [wp-cli/extension-command#278]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

The error occurs when I try to uninstall jetpack plugin

```
Uninstalled and deleted 'jetpack' plugin.
Success: Uninstalled 1 of 1 plugins.
PHP Fatal error:  Uncaught RuntimeException: Failed to locate plugin /var/www/wp-content/plugins/jetpack in /var/www/wp-content/plugins/jetpack/vendor/jetpack-autoloader/class-plugin-locator.php:47
Stack trace:
#0 /var/www/wp-content/plugins/jetpack/vendor/jetpack-autoloader/class-plugins-handler.php(99): Automattic\Jetpack\Autoloader\jp84939e330244e4e15279abc789e679bf\Plugin_Locator->find_current_plugin()
#1 /var/www/wp-content/plugins/jetpack/vendor/jetpack-autoloader/class-autoloader.php(106): Automattic\Jetpack\Autoloader\jp84939e330244e4e15279abc789e679bf\Plugins_Handler->get_active_plugins()
#2 /var/www/wp-includes/class-wp-hook.php(287): Automattic\Jetpack\Autoloader\jp84939e330244e4e15279abc789e679bf\Autoloader::Automattic\Jetpack\Autoloader\jp84939e330244e4e15279abc789e679bf\{closure}()
#3 /var/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#4 /var/www/wp-includes/plugin.php(484): WP_Hook->do_action()
#5 /var/www/wp-includes/load.php(1052): do_action()
#6 [internal function]: shutdown_action_hook()
#7 {main}
  thrown in /var/www/wp-content/plugins/jetpack/vendor/jetpack-autoloader/class-plugin-locator.php on line 47
```

**Describe how other contributors can replicate this bug**

> wp plugin install jetpack
> wp plugin uninstall jetpack

**Describe what you would expect as the correct outcome**

No errors, just uninstall the plugin.

**Let us know what environment you are running this on**

```
OS:     Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.3
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/html
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0
```

**Provide a possible solution**

No idea.

**Provide additional context/Screenshots**

It looks like the plugin is able to register some hooks before removing and throws the error after removing the source files.

**Comment by plesk-eponkin** [comment]
Closed because of https://github.com/Automattic/jetpack/issues/18996
